# Generated by Django 2.2.7 on 2019-11-14 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busstop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('place', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='hrtc.Busstop')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_point', to='hrtc.Busstop')),
            ],
        ),
    ]
