# Generated by Django 2.2.7 on 2019-11-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrtc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buses',
            new_name='Busses',
        ),
    ]
