# Generated by Django 2.2.7 on 2019-11-14 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrtc', '0003_auto_20191114_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='bus_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=9),
            preserve_default=False,
        ),
    ]
